type = mmap
filename = /tmp/shmcache-attach-mmap
logdir = /tmp
recycle_valid = true
max_mem_mb = 16
min_mem_mb = 0
segment_size = 1M
block_size = 64K
max_key_size = 128
max_key_count = 2
max_value_size = 64K
try_r_lk_interval = 1
try_w_lk_interval = 1
detect_r_dl_ticks = 100
detect_w_dl_ticks = 100
